# Generated by Django 4.1.2 on 2022-10-06 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='TypeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('description', models.TextField(default='', max_length=800, verbose_name='Полное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updateted_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='statuses', to='issuetracker.statusissue', verbose_name='Статус')),
                ('type_issue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='types', to='issuetracker.typeissue', verbose_name='Тип')),
            ],
        ),
    ]
