# Generated by Django 4.1.2 on 2022-10-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0002_remove_issue_type_issue_issue_type_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(default='New', on_delete=django.db.models.deletion.RESTRICT, related_name='statuses', to='issuetracker.statusissue', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type_issue',
            field=models.ManyToManyField(blank=True, default='Task', related_name='issues', to='issuetracker.typeissue', verbose_name='Тип'),
        ),
    ]
