# Generated by Django 4.1.2 on 2022-10-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0003_alter_issue_status_alter_issue_type_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', max_length=800, verbose_name='Описание')),
                ('date_begin', models.DateField(max_length=10, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, default='', max_length=10, verbose_name='Дата окончания')),
            ],
        ),
    ]
