# Generated by Django 4.1.2 on 2022-10-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(default='', max_length=10, verbose_name='Дата окончания'),
        ),
    ]
