# Generated by Django 4.1.2 on 2022-10-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0005_alter_project_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(blank=True, default='', max_length=10, null=True, verbose_name='Дата окончания'),
        ),
    ]
